import { Router, Request, Response, NextFunction } from 'express';
import multer from 'multer';
import { verifyAndEnableTwoFactorService } from '../../../../services/two_factor/two_factor_service';
import { requireBearerAuth } from '../../../../middlewares/auth';
import { ValidationError } from '../../../../utils/errors';
import { setupLogger } from '../../../../utils/logger';
import { getAppSettings } from '../../../../config/settings';
import { HTTP } from '../../../../schemas/common/baseResponse';
import { buildResponse } from '../../../../utils/response_builder';
import { zodValidation } from '../../../../utils/zod_validation';
import { TwoFactorVerifySchema } from '../../../../schemas/two_factor/zod/two_factor_verify_schema';

const _APP_SETTINGS = getAppSettings();
const logger = setupLogger(_APP_SETTINGS.log_level);

export const twoFactorVerifyRouter = Router();
const upload = multer();

/**
 * @openapi
 * /api/v1/two-factor/verify:
 *   post:
 *     tags:
 *       - Two Factor Authentication
 *     summary: Verify and enable 2FA
 *     description: |
 *       Verifies a TOTP code and enables 2FA if the code is correct.
 *       - Must be called after setting up 2FA with /setup
 *       - Verifies the 6-digit code generated by the authenticator app
 *       - If correct, permanently enables 2FA for the user
 *       - Returns **recovery codes** (10) and an **access_token** with full access
 *     security:
 *       - bearerAuth: []
 *     parameters: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               token:
 *                 type: string
 *                 pattern: '^\\d{6}$'
 *                 description: 6-digit code generated by the authenticator app
 *             required:
 *               - token
 *           example:
 *             token: "123456"
 *         multipart/form-data:
 *           schema:
 *             type: object
 *             properties:
 *               token:
 *                 type: string
 *                 pattern: '^\\d{6}$'
 *             required:
 *               - token
 *           example:
 *             token: "123456"
 *     responses:
 *       200:
 *         description: 2FA enabled and recovery codes generated
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/BaseResponseTwoFactorVerify'
 *             examples:
 *               success:
 *                 summary: Verification successful
 *                 value:
 *                   success: true
 *                   data:
 *                     success: true
 *                     message: '2FA enabled successfully.'
 *                     user_id: 1
 *                     role_name: "member"
 *                     recovery_codes: ['ABCD-EFGH-IJKL', 'MNOP-QRST-UVWX']
 *                     access_token: '<JWT>'
 *                   message: 'Two-factor verification processed'
 *       400:
 *         description: Validation error (invalid token)
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/BaseErrorResponse'
 *             examples:
 *               invalid_token:
 *                 summary: Invalid token
 *                 value:
 *                   success: false
 *                   data: null
 *                   message: 'Invalid verification code.'
 *       401:
 *         description: Unauthorized
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/BaseErrorResponse'
 *             examples:
 *               unauthorized:
 *                 summary: Unauthorized
 *                 value:
 *                   success: false
 *                   data: null
 *                   message: 'User not authenticated.'
 *       404:
 *         description: User not found or 2FA setup does not exist
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/BaseErrorResponse'
 *             examples:
 *               not_found:
 *                 summary: Not found
 *                 value:
 *                   success: false
 *                   data: null
 *                   message: 'No 2FA configuration found for this user.'
 *       409:
 *         description: 2FA already enabled for this user
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/BaseErrorResponse'
 *             examples:
 *               conflict:
 *                 summary: Conflict
 *                 value:
 *                   success: false
 *                   data: null
 *                   message: '2FA is already enabled for this user.'
 *       500:
 *         description: Internal server error
 */
twoFactorVerifyRouter.post('/verify', requireBearerAuth, upload.none(), async (req: Request, res: Response, next: NextFunction) => {
  try {
    const userId = Number((req as any).userId);
    logger.info('[2FA] Verify attempt', { userId });
    if (!Number.isFinite(userId) || userId <= 0) {
      throw new ValidationError('User not authenticated.', 401);
    }

    const { token } = zodValidation(TwoFactorVerifySchema, req.body);
    const result = await verifyAndEnableTwoFactorService(userId, token);
    logger.info('[2FA] Verify successful', { userId });
    buildResponse(res, HTTP.OK, result, 'Two-factor verification processed');
  } catch (err: any) {
    const message = err?.message ?? 'Error verifying 2FA';
    if (err instanceof ValidationError) {
      logger.warn(message);
    } else {
      logger.error(message);
    }
    next(err);
  }
});
